branches:
  only:
    - main

language: java
jdk:
  - oraclejdk11

before_install:
  - chmod +x mvnw
  - ./mvnw versions:set -DnewVersion=${TRAVIS_COMMIT}

script:
  - ./mvnw -B clean install

git:
  depth: false
  quiet: true
