# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches:
      - main

jobs:
  lint-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "15"
          distribution: "adopt"
          server-id: "ossrh"
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: lint
        run: ./mvnw clean install -Plint -B --no-transfer-progress

      - name: set new version to maven
        if: ${{ github.event.pull_request.merged == true }}
        run: ./mvnw versions:set -DnewVersion="${GITHUB_RUN_NUMBER}-${GITHUB_SHA}" -B --no-transfer-progress

      - name: build and deploy
        if: ${{ github.event.pull_request.merged == true }}
        env:
          OSSRH_NEXUS_USERNAME: ${{ secrets.OSSRH_NEXUS_USERNAME }}
          OSSRH_NEXUS_PASSWORD: ${{ secrets.OSSRH_NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./mvnw clean deploy -Pdeploy-to-maven-central -s settings.xml -B --no-transfer-progress
#    - name: tag new version
#      uses: EndBug/latest-tag@v1.4.0
#      with:
#        tag-name: v${GITHUB_RUN_NUMBER}
