name: version should be declared as maven property

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main

jobs:
  findDirtyVersionTags:
    name: version
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run script
        run: ./shellscript/ensure_property_is_used_for_version.sh
