name: version should be declared as maven property

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
    findDirtyVersionTags:
        name: version
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: run script
              run: ./shellscript/ensure_propert_is_used_for_version.sh
