name: find updates of dependencies or plugins

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
    updateVersions:
        name: update check
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                java-version: '15'
                distribution: 'adopt'
            - name: '(hopefully dont) find updates'
              run: /bin/bash -c "./mvn versions:display-property-updates -B --no-transfer-progress | grep --files-without-match 'updates are available'"
